#!/bin/bash
echo Making book chapter 
mkdir -p chapter
pandoc chapter.txt --biblio bib/refs.bib --csl csl/chicago-author-date.csl --toc --mathjax -s -o ./chapter/chapter.html
pandoc chapter.txt --biblio bib/refs.bib --csl csl/chicago-author-date.csl --toc -H chapterHeader.tex -o ./chapter/chapter.pdf
pandoc chapter.txt --biblio bib/refs.bib --csl csl/chicago-author-date.csl --toc -s -S -H chapterHeader.tex -o ./chapter/chapter.tex 

: <<'END'
pandoc test.txt --biblatex --biblio test.bib --csl chicago-author-date.csl -o ./test/test.pdf
pandoc --biblatex -s -S test.txt  --bibliography=test.bib --csl chicago-author-date.csl -o ./test/test.tex
cp test.bib test/test.bib
cd test
latex test.tex
bibtex test
latex test.tex
pdflatex test
cd ..
END