#!/bin/bash
for i in $( ls *.slides ); do

    echo Making $i into slides
    mkdir -p beamer
    pandoc -t beamer $i -o ./beamer/${i%.*}.pdf

done

for i in $( ls *.txt ); do

    echo "Converting" $i "to tex"
    mkdir -p tex
    pandoc -s -S $i -o ./tex/${i%.*}.tex --biblio refs.bib --biblatex --csl=nature.csl

#    echo Converting ${i##*.}.tex into pdf using pdflatex
#    cd tex
#    latex ${i%.*}.tex
#    pdflatex ${i%.*}
#    cd ..

    echo "Converting" $i "to PDF"
    mkdir -p pdf
    pandoc -s -S $i -o ./pdf/${i%.*}.pdf --biblio refs.bib --csl=nature.csl

    echo Converting $i to html
    mkdir -p html
    pandoc -s -S $i -o ./html/${i%.*}.html --biblio refs.bib --csl=nature.csl
    echo Converting $i to docx
    mkdir -p docx
    pandoc -s -S $i -o ./docx/${i%.*}.docx --biblio refs.bib --csl=nature.csl

    echo Converting $i to epub
    mkdir -p epub
    pandoc -s -S $i -o ./epub/${i%.*}.epub --biblio refs.bib --csl=nature.csl

done
